console.log("Hello git")
console.log("added for second commit)
console.log("new rest hard checking")
console.log("for checking 2 blob object creation")
console.log("from branch1")
console.log("new change on line 6 by main")
